#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# For the 'completion' prezto plugin (zsh-completions, internally)
autoload -U compinit; compinit

alias ls='ls --color=auto'
alias ll='ls -l'
alias vi='nvim'
alias nvimdiff='nvim -d'
alias vimdiff='nvimdiff'
export VISUAL="nvim"
export EDITOR="nvim"

set -o vi

export LANG=en_US.UTF-8

export REPOS=$HOME/repos

# Load Git completion
zstyle ':completion:*:*:git:*' script ~/.zsh/git-completion.bash
fpath=(~/.zsh $fpath)

export VISUAL=vim
export EDITOR=vim

export PATH=$PATH:$HOME/bin

export PATH=$PATH:/usr/local/go/bin
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

export PATH=$PATH:$HOME/pkg/protoc/bin

# rust
source $HOME/.cargo/env
export PATH=$PATH:$HOME/.cargo/bin

# python (installed by brew)
if [[ $(uname) == "Darwin" ]]; then
  export PATH=/opt/homebrew/opt/python@3.10/bin:/opt/homebrew/opt/python@3.10/libexec/bin:$PATH
fi

# pbcopy
if [[ $(uname) != "Darwin" ]]; then
  alias pbcopy='xclip -selection clipboard'
fi

# fzf: follow symlinks and include hidden files
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'

# homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# flutter
export PATH=$PATH:$HOME/flutter/bin

# nim
export PATH=$HOME/.nimble/bin:$PATH

# ruby
eval "$(rbenv init - zsh)"

# IntelliJ IDEA
if [[ $(uname) == "Darwin" ]]; then
  export PATH=$PATH:"/Applications/IntelliJ IDEA.app/Contents/MacOS"
fi

# GPG
export GPG_TTY=$(tty)
