#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# For the 'completion' prezto plugin (zsh-completions, internally)
autoload -U compinit; compinit

alias ls='ls --color=auto'
alias ll='ls -l'
alias vi='nvim'
alias nvimdiff='nvim -d'
alias vimdiff='nvimdiff'
export VISUAL="nvim"
export EDITOR="nvim"

set -o vi

export LANG=en_US.UTF-8

export REPOS=$HOME/repos

# Load Git completion
zstyle ':completion:*:*:git:*' script ~/.zsh/git-completion.bash
fpath=(~/.zsh $fpath)

export VISUAL=vim
export EDITOR=vim

export PATH=$PATH:$HOME/bin

export PATH=$PATH:/usr/local/go/bin
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

export PATH=$PATH:$HOME/pkg/protoc/bin

# rust
source $HOME/.cargo/env
export PATH=$PATH:$HOME/.cargo/bin

# pip install path
export PATH=$PATH:$HOME/.local/bin

# pbcopy
alias pbcopy='xclip -selection clipboard'

# fzf: follow symlinks and include hidden files
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'

# homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
