#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Enable profiler
#zmodload zsh/zprof

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# For the 'completion' prezto plugin (zsh-completions, internally)
autoload -U compinit; compinit

alias ls='ls --color=auto'
alias ll='ls -l'
alias cl='column -s, -t'
alias nvimdiff='nvim -d'
export VISUAL=nvim
export EDITOR=nvim

set -o vi

export LANG=en_US.UTF-8

export REPOS=$HOME/repos

# Load Git completion
zstyle ':completion:*:*:git:*' script ~/.zprezto/git-completion.bash
fpath=(~/.zsh $fpath)

export PATH=$PATH:$HOME/bin

export PATH=$PATH:/usr/local/go/bin:$HOME/.local/bin
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

export PATH=$PATH:$HOME/pkg/protoc/bin

# rust
export PATH=$PATH:$HOME/.cargo/bin

# python (installed by brew)
if [[ $(uname) == "Darwin" ]]; then
  export PATH=/opt/homebrew/opt/python@3.10/bin:/opt/homebrew/opt/python@3.10/libexec/bin:$PATH
fi

# pbcopy
if [[ $(uname) != "Darwin" ]]; then
  #alias pbcopy='xclip -selection clipboard'
  alias pbcopy='wl-copy'
fi

# fzf: follow symlinks and include hidden files
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'

# homebrew
if [[ $(uname) == "Darwin" ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# flutter
export PATH=$PATH:$HOME/flutter/bin

# ruby
#eval "$(rbenv init - zsh)"

# IntelliJ IDEA
if [[ $(uname) == "Darwin" ]]; then
  export PATH=$PATH:"/Applications/IntelliJ IDEA.app/Contents/MacOS"
fi

# GPG
export GPG_TTY=$(tty)
# Run GPG daemon manually only on macOS. In Linux, it's started automatically as a service.
if [[ $(uname) == "Darwin" ]]; then
  export GPG_TTY=$(tty)
  if ! pgrep -x "gpg-agent" > /dev/null; then
      eval $(gpg-agent --daemon)
  fi
fi

# yarn
export PATH=$PATH:$HOME/.yarn/bin

# PyCharm
if [[ $(uname) != "Darwin" ]]; then
  export PATH=/opt/pycharm-professional/bin:$PATH
fi

# ssh-agent
if [[ $(uname) != "Darwin" ]]; then
  export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
  # Let keychain run `ssh-add` automatically
  eval $(keychain --eval --quiet id_ed25519)
fi

# Run direnv automatically
eval "$(direnv hook zsh)"

# OpenBLAS
if [[ $(uname) == "Darwin" ]]; then
  export LDFLAGS="-L/opt/homebrew/opt/openblas/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/openblas/include"
  export PKG_CONFIG_PATH="/opt/homebrew/opt/openblas/lib/pkgconfig"
fi

# fnm
export PATH="/Users/yjlee/.local/state/fnm_multishells/32923_1770602308539/bin":$PATH
export FNM_MULTISHELL_PATH="/Users/yjlee/.local/state/fnm_multishells/32923_1770602308539"
export FNM_VERSION_FILE_STRATEGY="local"
export FNM_DIR="/Users/yjlee/.local/share/fnm"
export FNM_LOGLEVEL="info"
export FNM_NODE_DIST_MIRROR="https://nodejs.org/dist"
export FNM_COREPACK_ENABLED="false"
export FNM_RESOLVE_ENGINES="true"
export FNM_ARCH="arm64"
rehash

# zellij
alias z='zellij'

export PATH=~/.npm-global/bin:$PATH

alias t="$HOME/repos/me/arch/scripts/deepl.sh"
alias tk="$HOME/repos/me/arch/scripts/deepl.sh ko"
alias te="$HOME/repos/me/arch/scripts/deepl.sh en"

# Finish profiling
#zprof
